<?php

namespace AppBundle\Repository;

/**
 * AnnouncementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnnouncementRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAnnouncements(int $page)
    {
        $onPage = 20;

        $qb = $this->_em->createQueryBuilder();
        $qb->select('announcement');
        $qb->from('AppBundle:Announcement', 'announcement');

        $qb->orderBy('announcement.id', 'DESC');
        $qb->setMaxResults($onPage);
        $qb->setFirstResult($page * $onPage);

        return $qb->getQuery()->getResult();
    }

    public function countAnnouncements()
    {
        $qb = $this->_em->createQueryBuilder();
        $qb->select('COUNT(announcement.id)');
        $qb->from('AppBundle:Announcement', 'announcement');

        return $qb->getQuery()->getSingleScalarResult();
    }
}
