<?php

namespace AppBundle\Repository;

/**
 * BerryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BerryRepository extends \Doctrine\ORM\EntityRepository
{
}
