<?php

namespace AppBundle\Repository;

/**
 * CronRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CronRepository extends \Doctrine\ORM\EntityRepository
{
}
