<?php

namespace AppBundle\Repository;

/**
 * ExchangePokemonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExchangePokemonRepository extends \Doctrine\ORM\EntityRepository
{
}
