<?php

namespace AppBundle\Repository;

/**
 * FriendRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FriendRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllFriends(int $userId)
    {
        return $this->createQueryBuilder('f')
            ->where('f.userId = :id')
            ->orWhere('f.whoId = :id')
            ->andWhere('f.accepted = 1')
            ->setParameter(':id', $userId)
            ->getQuery()
            ->getResult();
    }

    public function getAllInvitations(int $userId)
    {
        return $this->createQueryBuilder('f')
            ->Where('f.whoId = :id')
            ->andWhere('f.invitation = 1')
            ->andWhere('f.accepted = 0')
            ->setParameter(':id', $userId)
            ->getQuery()
            ->getResult();
    }

    public function getAllSentInvitations(int $userId)
    {
        return $this->createQueryBuilder('f')
            ->where('f.userId = :id')
            ->andWhere('f.invitation = 1')
            ->andWhere('f.accepted = 0')
            ->setParameter(':id', $userId)
            ->getQuery()
            ->getResult();
    }

    public function getOneFriendship(int $id, int $userId)
    {
        return $this->createQueryBuilder('f')
            ->where('f.userId = :uId')
            ->orWhere('f.whoId = :uId')
            ->andWhere('f.accepted = 1')
            ->andWhere('f.id = :id')
            ->setParameter(':uId', $userId)
            ->setParameter(':id', $id)
            ->getQuery()
            ->getOneOrNullResult();
    }

    public function checkIfUserSentInvitation(int $id, int $userId)
    {
        return $this->findOneBy([
            'userId' => $id,
            'whoId' => $userId,
            'invitation' => 1
        ]);
    }

    public function checkIfUserReceivedInvitation(int $id, int $userId)
    {
        return $this->findOneBy([
            'whoId' => $id,
            'userId' => $userId,
            'invitation' => 1
        ]);
    }

    public function getOneInvitation(int $id, int $userId)
    {
        return $this->findOneBy([
            'id' => $id,
            'whoId' => $userId,
            'invitation' => 1
        ]);
    }

    public function getOneSentInvitation(int $id, int $userId)
    {
        return $this->findOneBy([
            'id' => $id,
            'userId' => $userId,
            'invitation' => 1
        ]);
    }
}
