<?php

namespace AppBundle\Repository;

/**
 * MarketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MarketRepository extends \Doctrine\ORM\EntityRepository
{
    public function countOferts(string $name, string $kind, bool $own, int $userId): int
    {
        $qb = $this->_em->createQueryBuilder();
        $qb->select('COUNT(ofert.id)');
        $qb->from('AppBundle:Market', 'ofert');
        $qb->where('ofert.name = :name');
        $qb->andWhere('ofert.kind = :kind');
        if (!$own) {
            $qb->andWhere('pokemon.ownerId <> :idUser');
            $qb->setParameter(':idUser', $userId);
        }
        $qb->setParameter(':name', $name);
        $qb->setParameter(':kind', $kind);
        $qb->orderBy('ofert.id', 'ASC');

        return $qb->getQuery()->getSingleScalarResult();
    }

    public function getOferts(string $name, string $kind, bool $own, int $userId, int $page)
    {
        $onPage = 30;

        $qb = $this->_em->createQueryBuilder();
        $qb->select('ofert');
        $qb->from('AppBundle:Market', 'ofert');
        $qb->where('ofert.name = :name');
        $qb->andWhere('ofert.kind = :kind');
        if (!$own) {
            $qb->andWhere('ofert.userId <> :userId');
            $qb->setParameter(':userId', $userId);
        }
        $qb->setParameter(':name', $name);
        $qb->setParameter(':kind', $kind);
        $qb->orderBy('ofert.id', 'ASC');
        $qb->setMaxResults($onPage);
        $qb->setFirstResult($page * $onPage);

        return $qb->getQuery()->getResult();
    }
}
