<?php

namespace AppBundle\Repository;

/**
 * PokemonTrainingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PokemonTrainingRepository extends \Doctrine\ORM\EntityRepository
{
}
