<?php

namespace AppBundle\Repository;

/**
 * PokeballRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PokeballRepository extends \Doctrine\ORM\EntityRepository
{
}
