<?php

namespace AppBundle\Repository;

/**
 * StatisticRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatisticRepository extends \Doctrine\ORM\EntityRepository
{

    public function addCatchedOnePokemon(int $userId)
    {
        $this->createQueryBuilder('s')
            ->update()
            ->set('s.catched', '(s.catched + 1)')
            ->where('s.id = :id')
            ->setParameter('id', $userId)
            ->getQuery()
            ->execute();
    }
}
