<?php

namespace AppBundle\Repository;

/**
 * StonesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StonesRepository extends \Doctrine\ORM\EntityRepository
{
}
